/**
 * Step 4b: build the unified UI dictionary for the flagship app.
 * Priority sources per language (largest/most complete first):
 *   en/zh-TW/ja/ko/vi  -> Vietnamese Food Master (232 keys, most evolved template)
 *   zh-TW fallback tw  ; th -> Korean Food Master (153) ; fil -> Filipino app ; ms -> Malaysia app
 * Every key at every level is filled using the first source that defines it;
 * final fallback is EN (flagged in the report).
 */
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const BASE = 'C:/Users/Matrixkuo/Desktop/Antigravity/APP Design/';
const TMP = path.join(ROOT, 'scripts', '.tmp-bundles');

const DICTS = {
  tw: 'Taiwan',
  th: 'ThaiFood Master',
  jp: 'Japan Food Master',
  kr: 'Korean Food Master',
  my: 'Malaysia Food Master',
  ph: 'Filipino Food Master',
  vn: 'Vietnamese Food Master',
};

const LANG_SOURCES = {
  en: ['vn', 'tw', 'my', 'kr', 'ph', 'th', 'jp'],
  'zh-TW': ['vn', 'tw', 'my', 'kr', 'ph', 'th', 'jp'],
  ja: ['vn', 'tw', 'my', 'kr', 'ph', 'th', 'jp'],
  ko: ['vn', 'tw', 'my', 'kr', 'ph', 'th', 'jp'],
  th: ['kr', 'th', 'jp'],
  vi: ['vn', 'tw'],
  fil: ['ph'],
  ms: ['my'],
};

function loadDict(dir) {
  const entry = path.join(BASE, dir, 'src', 'i18n', 'translations.ts');
  if (!fs.existsSync(entry)) throw new Error('missing ' + entry);
  const outfile = path.join(TMP, 'i18n_' + dir.replace(/[^\w]+/g, '_') + '.cjs');
  esbuild.buildSync({ entryPoints: [entry], outfile, bundle: true, platform: 'node', format: 'cjs', logLevel: 'silent' });
  const mod = require(outfile);
  return mod.translations || mod.default || mod.default?.translations || null;
}

function isPlainObject(v) {
  return v && typeof v === 'object' && !Array.isArray(v);
}

/** recursive merge: target objects KEEP missing paths from later sources */
function mergeDeep(target, source) {
  for (const [k, v] of Object.entries(source || {})) {
    if (target[k] === undefined) {
      target[k] = v;
    } else if (isPlainObject(target[k]) && isPlainObject(v)) {
      mergeDeep(target[k], v);
    } else if (isPlainObject(target[k]) && !isPlainObject(v)) {
      target[k] = mergeKeyValueObj(target[k], v);
    }
  }
  return target;
}
function mergeKeyValueObj(targetObj, v) {
  // same shape key->string; skip values already defined
  for (const [k, val] of Object.entries(v || {})) {
    if (targetObj[k] === undefined) targetObj[k] = val;
  }
  return targetObj;
}

function flatKeys(obj, prefix = '') {
  const out = new Set();
  for (const [k, v] of Object.entries(obj || {})) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      flatKeys(v, prefix + k + '.').forEach((x) => out.add(x));
    } else out.add(prefix + k);
  }
  return out;
}

const loaded = {};
for (const [key, dir] of Object.entries(DICTS)) loaded[key] = loadDict(dir);

const translations = {};
const report = {};
for (const [L, priority] of Object.entries(LANG_SOURCES)) {
  const sources = priority.map((p) => loaded[p]?.[L]).filter(Boolean);
  const dict = mergeDeep({}, ...sources);
  report[L] = { keys: flatKeys(dict).size, primary: priority[0], contributors: sources.length ? priority : [] };
  translations[L] = sortDeep(dict);
}

function sortDeep(obj) {
  if (!isPlainObject(obj)) return obj;
  const out = {};
  for (const k of Object.keys(obj).sort()) out[k] = sortDeep(obj[k]);
  return out;
}

const body = JSON.stringify(translations, null, 1);
fs.mkdirSync(path.join(ROOT, 'src', 'i18n'), { recursive: true });
const content =
  `import type { Language } from '../types/unified';\n\n` +
  `// Auto-generated by scripts/build_translations.cjs — do not edit by hand.\n` +
  `export type Dictionary = Record<string, unknown>;\n\n` +
  `export const translations: Record<Language, Dictionary> = ${body};\n`;
fs.writeFileSync(path.join(ROOT, 'src', 'i18n', 'translations.ts'), content);
fs.writeFileSync(path.join(ROOT, 'scripts', 'i18n_merge_report.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
console.log('written src/i18n/translations.ts', body.length, 'bytes');
