/**
 * Step 3 converter: load the 7 country source projects' recipe data (READ-ONLY),
 * normalize to the unified CountryRecipe schema, copy referenced images into
 * public/images/<country>/ and emit src/data/<country>.ts data packs.
 *
 * Uses esbuild (bundled with vite) so TS imports resolve exactly like the app build.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BASE = 'C:/Users/Matrixkuo/Desktop/Antigravity/APP Design/';
const TMP = path.join(ROOT, 'scripts', '.tmp-bundles');

const SOURCES = [
  { country: 'tw', label: 'Taiwan', dir: 'Taiwan', slug: 'tw' },
  { country: 'th', label: 'Thailand', dir: 'ThaiFood Master', slug: 'th' },
  { country: 'jp', label: 'Japan', dir: 'Japan Food Master', slug: 'jp' },
  { country: 'kr', label: 'Korea', dir: 'Korean Food Master', slug: 'kr' },
  { country: 'my', label: 'Malaysia', dir: 'Malaysia Food Master', slug: 'my' },
  { country: 'ph', label: 'Philippines', dir: 'Filipino Food Master', slug: 'ph' },
  { country: 'vn', label: 'Vietnam', dir: 'Vietnamese Food Master', slug: 'vn' },
];

const esbuild = require('esbuild');

function loadCountry(dir) {
  const candidates = [
    path.join(BASE, dir, 'src', 'data', 'recipes.ts'),
    path.join(BASE, dir, 'src', 'data', 'recipes', 'index.ts'),
  ];
  const entry = candidates.find((c) => fs.existsSync(c));
  if (!entry) throw new Error('entry missing for ' + dir);
  const outfile = path.join(TMP, dir.replace(/[^\w]+/g, '_') + '.cjs');
  esbuild.buildSync({
    entryPoints: [entry],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'cjs',
    logLevel: 'silent',
    external: ['react', 'react-dom'],
  });
  const mod = require(outfile);
  const recipes = mod.recipes || mod.default || mod.default?.recipes;
  if (!Array.isArray(recipes)) throw new Error('no recipes array from ' + dir);
  return recipes;
}

// native naming field per country in the source culture objects
const NATIVE_FIELDS = {
  kr: ['koreanScript', 'koreanPhonetics'],
  jp: ['japaneseKanji', 'japaneseKana', 'japaneseRomaji'],
  th: ['thaiScript', 'thaiPronunciation'],
  tw: ['chineseScript', 'chinesePronunciation', 'hanziScript'],
  vi: ['vietnameseScript', 'vietnameseName'],
  my: ['malayName', 'malayScript'],
  ph: ['filipinoName', 'tagalogName'],
};

function unifyRecipe(rec, src) {
  const culture = { ...(rec.culture || {}) };
  const nf = NATIVE_FIELDS[src.country] || [];

  // unify native naming into a single accessor shape, keep originals too
  culture.nativeName = culture.nativeName || culture[nf[0]] || culture[nf[1]] || culture.japaneseRomaji;
  culture.nativePhonetics =
    culture.nativePhonetics ||
    culture[nf[1]] ||
    culture.japaneseRomaji ||
    culture.koreanPhonetics;

  return {
    country: src.country,
    ...rec,
    culture,
  };
}

function collectImages(obj, set) {
  if (typeof obj === 'string') {
    if ((obj.startsWith('/images/') || obj.startsWith('images/')) && obj.includes('.')) {
      set.add(obj.startsWith('/') ? obj.slice(1) : obj);
    }
    return;
  }
  if (Array.isArray(obj)) { obj.forEach((v) => collectImages(v, set)); return; }
  if (obj && typeof obj === 'object') { Object.values(obj).forEach((v) => collectImages(v, set)); }
}

async function main() {
  fs.mkdirSync(TMP, { recursive: true });
  fs.mkdirSync(path.join(ROOT, 'src', 'data'), { recursive: true });
  const report = [];
  const copied = [];

  for (const src of SOURCES) {
    const raw = loadCountry(src.dir);
    const recipes = raw.map((r) => unifyRecipe(r, src));

    // images
    const imgs = new Set();
    collectImages(recipes, imgs);
    const imgMap = new Map();
    for (const rel of imgs) {
      const from = path.join(BASE, src.dir, 'public', rel);
      if (!fs.existsSync(from)) continue; // missing asset -> logged, path kept (UI falls back)
      const toRel = path.join('images', src.slug, rel.replace(/^images\//, ''));
      const to = path.join(ROOT, 'public', toRel);
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
      imgMap.set('/' + rel.replaceAll('\\', '/'), '/' + toRel.replaceAll('\\', '/'));
      copied.push({ country: src.country, rel });
    }

    // rewrite image paths in the emitted data
    let json = JSON.stringify(recipes);
    for (const [from, to] of imgMap) {
      json = json.split('"' + from + '"').join('"' + to + '"');
    }
    json = json
      .replace(/\u2028/g, '\\u2028')
      .replace(/\u2029/g, '\\u2029');

    const outFile = path.join(ROOT, 'src', 'data', `recipes-${src.slug}.ts`);
    const content =
      `import type { CountryRecipe } from '../types/unified';\n\n` +
      `// Auto-generated by scripts/merge_recipes.mjs — do not edit by hand.\n` +
      `export const recipes: CountryRecipe[] = ${json};\n`;
    fs.writeFileSync(outFile, content);

    report.push({
      country: src.country,
      label: src.label,
      recipes: recipes.length,
      images: imgMap.size,
      bytes: content.length,
    });
  }

  console.log(JSON.stringify(report, null, 2));
  const miss = report.reduce((a, r) => a + r.recipes, 0);
  console.log('TOTAL recipes:', report.reduce((a, r) => a + r.recipes, 0) || 0);
  fs.writeFileSync(
    path.join(__dirname, 'merge_report.json'),
    JSON.stringify({ report, imageCopies: copied }, null, 2)
  );
  console.log('image copies:', copied.length, '→ merge_report.json');
}

main().catch((err) => { console.error('ERROR:', err.message); process.exit(1); });
